# Generated by Django 5.2.7 on 2025-11-05 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_message_options_message_is_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblock',
            options={'verbose_name': 'User Block', 'verbose_name_plural': 'User Blocks'},
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='blocked',
            new_name='blocked_user',
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked_user')},
        ),
        migrations.AlterField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='reason',
        ),
    ]
