# Generated by Django 5.2.7 on 2025-11-05 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skillrequest',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='related_request',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_request',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_skill',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skillrequest',
            name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('meeting_invite', 'Meeting Invitation'), ('meeting_update', 'Meeting Update'), ('skill_request', 'Skill Request'), ('review', 'New Review'), ('skill_session', 'Skill Session Started'), ('skill_completed', 'Skill Session Completed'), ('email_verification', 'Email Verification')], default='message', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skillrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_user',
        ),
    ]
